server:
  port: 8080

spring:
  application:
    name: flight-search-service
#  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/flight-search}
#    username: ${SPRING_DATASOURCE_USERNAME:root}
#    password: ${SPRING_DATASOURCE_PASSWORD:root}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs