apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-search-service
  namespace: flight-comparator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-search-service
  template:
    metadata:
      labels:
        app: flight-search-service
    spec:
      serviceAccountName: ecr-access
      containers:
        - name: flight-search-service
          image: 162582596521.dkr.ecr.eu-west-1.amazonaws.com/flight-comparator/flight-search-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ecr-secret