apiVersion: v1
kind: Service
metadata:
  name: flight-search-service
spec:
  selector:
    app: flight-search-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer